### ISSUE TITLE
[feature request] rotate camera

### ISSUE THREAD

**Issue by ewtoombs** [DFHack/stonesense#36]
It'd be cool to have controls that rotate the camera +-90*. Stonesense has something similar, but it only works one way. Bidirectional would be better.

**Comment by JapaMala** [comment]
Press enter. Issue closed.

**Comment by lethosor** [comment]
Another potential issue with #32 here.

**Comment by DAOWAce** [comment]
What about rotating 45°?

This was the biggest issue I had with using stonesense as the overlay, because the controls were off by 45°.  I ended up resorting to the tile graphics, which is why I never bothered to play DF in the first place 2 years ago.

I now wanted to use stonesense to get a better looking overview of my world while on a second monitor, but it's still all rotated 45°.

Would help greatly if this was adjusted.
