### ISSUE TITLE
Crash on trade caravan

### ISSUE THREAD

**Issue by jmdejong** [DFHack/stonesense#54]
When trying to view tiles with a trade wagon, both stonesense and dwarffortress become unresponsive. The dwarf fortress window stops updating the screen.
The dfhack console still works.

No error message is generated.

Example save file with a trade caravan in the fortress: https://github.com/tildetown/tilde-df/tree/b2056a945ee5f6adbeb5a186e0cadc5cb0784d2b

I'm running this on 64bit Archlinux. I have tried both the AUR version (dfhack 0.43.05-r1), and a manual install of dfhack 0.43.05-r2.

I strongly suspect that it's the wagon causing the crash, but it's possible that some other part of the caravan is the cause.

**Comment by Vislar** [comment]
Seconded, 
Stonesense seems to hate trade wagons. Even though I use 0.43.03 32bit because of my older system at the moment, it seems like this bug applies to newer versions as well. Which is unfortunate.

**Comment by FalcoGer** [comment]
This is happening to me also.
Running Ubuntu 16.04 LST 64 bit with DF 0.43.05 + twbt + DFHack 0.43.05r2 installed with LNP.
DF just crashes along with dfhack and ssense when trying to view a tile that has a wagon. took me some time to figure it out.
no error message is given for anything.

**Comment by JapaMala** [comment]
I'll have a look and see what I can manage.

**Comment by NutchapolSal** [comment]
This is even worse on Windows 10 64bit (DF 0.44.05 + DFHack 0.44.05-r2)
Instantly crashes when a trade wagon exists, No "Not responding" (and destroying all progress after the last save)

At least I can now go back to my first fort after thinking DF can't handle it anymore and then making another fort

**Comment by Eilmanx** [comment]
Using DF version 44.09 on Windows 10.

Bug seems to be still there there. Trade caravan comes and crashes the game. When I used to play it in windows 7 system, I could manipulate Stonesense camera away from trading cart and evade crash that way. But now it doesn't work anymore, it crashes immediately when caravan enters to the map area. I tried to turn on/off all possible features in Stonsesense, but nothing helps. If someone could remove possibility to load trade caravans altogether in code, it might help, I have no better ideas.

**Comment by Random-txt** [comment]
has this been resolved? My game crashes right after i hear the trade music from soundsense. I am guessing that it is the trader who caused my crash.
Do i start a new game or, is there a solution?

**Comment by lethosor** [comment]
Can't you just run without stonesense?

**Comment by mianxiu** [comment]
I' has a same problem too.

**Comment by theicewolf23** [comment]
I have the same problem. 
I use PeridexisErrant's Starter Pack (64bit)  version 0.44.12-r04.
It happened on version version 0.44.12-r03 as well.
It happens repeatedly and consistently. The game is automatically paused. Whenever I move the screen to the newly arrived caravan the game and stonesense crashes, the DF and stonesense windows close and I lose the unsaved progress. The stderr.log in the directory Dwarf Fortress 0.44.12 reports nothing of the crash. What information do you need from me to fix this issue ?

**Comment by napagokc** [comment]
Absolutely the same as @theicewolf23 described.
Windows 7 x64, latest Masterwork pack (2.6.0.0 - DF 0.44.12, DFHack 0.44.12-r2 (release) on x86_64).

**Comment by lethosor** [comment]
> What information do you need from me to fix this issue ?

Since it seems to be pretty reproducible, it's unlikely to be specific to anyone's system. Really the only thing that can be provided is a save, which was provided in the first post. Error logs rarely contain useful information about crashes.

(Stonesense has historically been unstable on my primary system(s) so I can't fix this myself.)

**Comment by napagokc** [comment]
Just in case please have also my save, hope it'll help at least a bit :)
https://drive.google.com/open?id=1QfsB5Eazfa7U0tgP_6Pr6hT6pr-GwsaO

**Comment by napagokc** [comment]
Sooo.... I've been mighty curious and debugged the thing and found out that there's a nullptr exception at line 532 in Creatures.cpp. Simple check did the trick:
```
if(source->status.current_soul != nullptr) {
    furball.stress_level = source->status.current_soul->personality.stress_level;
}
```
But the wagon itself is displayed with mere "W" where it has the center.
![screenshot](https://user-images.githubusercontent.com/922882/61007440-83d84280-a375-11e9-8352-87d89c8b9d63.png)
Since I never saw it in life before - it's like that by design?

**Comment by lethosor** [comment]
That's definitely a likely cause. I'm honestly surprised that hadn't come up before - many creatures don't have souls, and that change (9c9d8a59d6f667cff4f503fc74fd084e0d0f617f) was introduced in 2014. I'll make that fix and hopefully it works.

I'm guessing there probably isn't a wagon sprite.

**Comment by lethosor** [comment]
I have posted builds with that fix for the systems that were mentioned above at https://files.dfhack.org/190710000/. Let me know if that works or if you would like builds for other systems. To upgrade stonesense:
* Copy hack/plugins/stonesense.plug.* from the zip to hack/plugins in your dfhack installation (it should overwrite the copy of stonesense that's already there)
* (Probably optional:) Copy the stonesense folder over the existing stonesense folder (I don't think it has changed at all since 0.44.12-r2, though, so you can probably skip this)

cc: @jmdejong @Vislar @FalcoGer @NutchapolSal @Eilmanx @Random-txt @mianxiu @theicewolf23

**Comment by The-Jester-Race** [comment]
I can confirm this fix worked for my Stonesense crash.  The human wagon appears as a "W" while the wagon I came in on is represented by Stonesense's iso graphic.

In Armok Vision the wagon actually displays but it is standing straight up in the air with whomever is driving it buried in the ground, not visible.

Regardless, it doesn't crash, which is great!  Thanks.
